version: "3.8"

services:
    node:
        build: ./docker/node
        volumes:
            - ./src:/application
        working_dir: /application
        ports:
            - "3389:3389"
        restart: always
